using System;
namespace MyApp
{
    public class Canlılar
    {
        protected void Beslenme()
        {
            Console.WriteLine("Canlılar Beslenir.");
        }

        protected void Solunum()
        {
            Console.WriteLine("Canlılar solunum yapar.");
        }

        protected void Boşaltım()
        {
            Console.WriteLine("Canlılar boşaltım yapar.");
        }
    }
}